Chef.create!([
  {name: "Kai Zimmer", age_string: 30, location: "London", styles: "Thai, German", biography: "Multilingual MBA candidate and IT sector professional with over six years of international experience in countries including Canada, France, and Romania. \r\nDirectly responsible for the delivery of over 15 successful software implementation projects for customers in automotive, retail, and manufacturing sectors. \r\nManaged a team of up to ten full-time employees. Introduced a partner enablement strategy successfully.", culinarytraining: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.", picture: "https://media.licdn.com/media/p/1/005/05e/052/2f50523.jpg", video: "https://www.youtube.com/watch?v=tf2HxCaKCB0", family_dinner: true, informal_reunion: true, number_of_helpers: 2, last_minute: true, teaching: true, min_size: 0, max_size: 3, facebook: "https://www.facebook.com/kai.zimmer", age: nil},
  {name: "Andrea", age_string: 25, location: "Bologna", styles: "Italian", biography: nil, culinarytraining: nil, picture: nil, video: nil, family_dinner: nil, informal_reunion: nil, number_of_helpers: nil, last_minute: nil, teaching: nil, min_size: nil, max_size: nil, facebook: nil, age: nil},
  {name: "Arnaud", age_string: 28, location: "Paris", styles: "French, Special", biography: nil, culinarytraining: nil, picture: nil, video: nil, family_dinner: nil, informal_reunion: nil, number_of_helpers: nil, last_minute: nil, teaching: nil, min_size: nil, max_size: nil, facebook: nil, age: nil},
  {name: "Rosa", age_string: 28, location: "Guadalajara", styles: "Mexican, Tex-Mex", biography: nil, culinarytraining: nil, picture: nil, video: nil, family_dinner: nil, informal_reunion: nil, number_of_helpers: nil, last_minute: nil, teaching: nil, min_size: nil, max_size: nil, facebook: nil, age: nil},
  {name: "Raul", age_string: 31, location: "Perú, Lima", styles: "Peruvian", biography: "", culinarytraining: "", picture: "", video: "", family_dinner: false, informal_reunion: false, number_of_helpers: nil, last_minute: false, teaching: false, min_size: nil, max_size: nil, facebook: "", age: nil}
])
Course.create!([
  {name: "Ciabatta con tomate", position: "1", type: nil, description: "", menu_id: 5, course_type: nil},
  {name: "Papaya Salad", position: "1", type: "", description: "A fresh salad", menu_id: 1, course_type: "Starter"},
  {name: "Red Thai Duck Curry", position: "2", type: nil, description: "Free-range duck in an amazing curry. Served with rice on a banana leaf.", menu_id: 1, course_type: "Main"},
  {name: "Fried Banana", position: "3", type: nil, description: "", menu_id: 1, course_type: "Dessert"}
])
Menu.create!([
  {name: "Red Kai Curry", price_string: 20.55, chef_id: 1, photo1: "http://upload.wikimedia.org/wikipedia/commons/e/e2/Red_roast_duck_curry.jpg", photo2: "", photo3: "", photo4: "", photo5: "", currency: "", description: "An incredibly spice and hot thai curry", cuisine_italian: false, cuisine_peruvian: false, cuisine_mediterranean: false, cuisine_spanish: false, cuisine_american: false, cuisine_japanese: false, cuisine_fusion: false, cuisine_thai: true, cuisine_vietnamese: false, cuisine_latinamerican: false, cuisine_indian: false, cuisine_persian: false, cuisine_bbq: false, cuisine_argentinian: false, cuisine_anticuchos: false, cuisine_patisserie: false, cuisine_exotic: false, cuisine_german: true, cuisine_brazilian: false, option_alcohol: true, option_change: true, hashtags: false, partysize: false, price: nil},
  {name: "Italian Evening Dinner", price_string: 0.0, chef_id: 2, photo1: nil, photo2: nil, photo3: nil, photo4: nil, photo5: nil, currency: nil, description: nil, cuisine_italian: nil, cuisine_peruvian: nil, cuisine_mediterranean: nil, cuisine_spanish: nil, cuisine_american: nil, cuisine_japanese: nil, cuisine_fusion: nil, cuisine_thai: nil, cuisine_vietnamese: nil, cuisine_latinamerican: nil, cuisine_indian: nil, cuisine_persian: nil, cuisine_bbq: nil, cuisine_argentinian: nil, cuisine_anticuchos: nil, cuisine_patisserie: nil, cuisine_exotic: nil, cuisine_german: nil, cuisine_brazilian: nil, option_alcohol: nil, option_change: nil, hashtags: nil, partysize: nil, price: nil}
])
